### ISSUE TITLE
Story Detail Page: Discussion of English translation Issue

### ISSUE THREAD

**Issue by elambrinaki** [PrincetonPEMM/pemm-issues#33]

**Comment by elambrinaki** [comment]
`ENGLISH TRANSLATION` field:

- [ ] Use column "Translation of Story into English" on the Canonical Story sheet. Then use two Google Docs from Wendy with PEMM translations; overwrite the data if a translation from the Canonical Story sheet has been added earlier (Wendy's files are more recent, so use them as the main source)

- [ ] If "English Translation Status" column has "Rough (unedited) translation", spell out "(Unedited translation)" before the text of the translation. If "English Translation Status" column has "Summary only", spell out "(Summary only)" before the text of the translation.

<img width="340" alt="4PEMM Story Detail page" src="https://user-images.githubusercontent.com/34317046/160263615-5357d2df-6adc-4bea-b5e6-8b784854988d.png">

**Comment by WendyLBelcher** [comment]
Re this comment "Use column "Translation of Story into English" on the Canonical Story sheet." I don't think we should do that. I think we should ignore that column for the following reasons. Feel free to disagree!
[11:43](https://pemmworkspace.slack.com/archives/D0112UGR788/p1648395803494959)
First, because we are working in the MS Word file, it is easier to keep track of information there. I'm not saying we should retire all those columns in the Google Sheet, but keeping three places up to date doesn't seem to be working well (that is, in the MS Word file, in the Translation progress sheet, and in the Translation columns). That is fine for working, but not for data import. And it is essential that we continue to keep good track in the Google Sheet of translators and the manuscript basis for the translation. But, we will have the most accurate information in the file where the translations actually live. (edited) 
[11:43](https://pemmworkspace.slack.com/archives/D0112UGR788/p1648395814143349)
Second, we can't do paragraph returns in that Translation of Story into English column, and so every translation there is already wrong. Many paragraph returns are essential to understanding these very dense stories.
[11:44](https://pemmworkspace.slack.com/archives/D0112UGR788/p1648395855168199)
Third, almost nothing in the "Translation of Story into English" has been edited, while some of the MS Word doc has. And a lot more is going to be. Taylor is going to work for us again this summer and I'm going to have him work systematically through this MS Word translation file. As part of this, the Budge translations in the column are not formatted properly in terms of returns and are not in our style and are full of Old English and sometimes even ethnically charged language. Since they are in the public domain, I'm going to include them in the MS word doc and have Taylor edit them and we will say they are updated Budge translations. We don't want him to translate the document and then transfer it so that again; that's how we get versioning problems. (edited) 
[11:45](https://pemmworkspace.slack.com/archives/D0112UGR788/p1648395953457259)
Fourth, I have formatted the MS Word translation document to have the relevant information. It should be fairly easy for Henok to program an import. I have the unique character | in front of every bit of information to be programmed. (Of course this will be less reliable than a column. Still, to have it right there will ensure that it is the most accurate in terms of credit.) So, ID (which is in the format "|ID 004"), worker (which is in the format "|Translated by Jeremy Brown and Dawit Muluneh"), status (which is in the format "|Edited by Wendy Laura Belcher" or "|Rough (unedited) translation"), and manuscript (which is in the format "|From BOR 520, f. 25"). I think that the last bit, manuscript, can best be imported from the Google sheet, but I keep it here so people can easily check translations. Also, the titles in the MS Word document should be ignored, the Google Sheet will be more accurate. But the translation itself, who translated the document, and who edited the translation will be best from this MS Word document.

**Comment by elambrinaki** [comment]
There are summaries (mainly done by Dawit, for example IDs 325, 304, 124, 128) that are in the English Translation column and NOT in the Google doc. Plus, all published translations are in the English Translation column only. I propose to import this column and _overwrite_ it with the content of Google docs in case of duplicates (as the Google docs have more recent versions of the edited stories).

**Comment by henokalem** [comment]
9) **Published translation**: (if "English Translation Status" column (column AO) has "Published translation", use "English Translation Source" column(column S), see https://github.com/WendyLBelcher/pemm-website/issues/30. Otherwise, spell "None".)

10) **Manuscript source for English translation**: (If there is no translation (English Translation Status column (column AO) is empty), skip this field. Otherwise, use columns English Translation Manuscript Name and English Translation Manuscript Folio)

11)**English translation author**: (if there is a published translation cited above, skip this field. If there is no translation (English Translation Status column is empty), skip this field. Otherwise, use English Translation Author)

**Comment by WendyLBelcher** [comment]
Style issue: We a line space to indicate a paragraph break, we do not use indents or tabs.
